defmodule ChatWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :chat

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_chat_key",
    signing_salt: "ZbEvDL7Y",
    same_site: "Lax"
  ]

  socket "/socket", ChatWeb.UserSocket,
    websocket: true,
    longpoll: false,
    check_origin: allowed_origins()

  # Origins allowed to open WebSocket connections to this socket.
  # Configure via CHAT_ALLOWED_ORIGINS (comma-separated), e.g.
  # "https://dev.zer0.tv,https://zer0.tv".
  defp allowed_origins do
    System.get_env("CHAT_ALLOWED_ORIGINS", "http://localhost:4000")
    |> String.split(",", trim: true)
    |> Enum.map(&String.trim/1)
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :chat,
    gzip: not code_reloading?,
    only: ChatWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :chat
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ChatWeb.Router
end
